### ISSUE TITLE
Version 2.3.0 - missing menu remind link

### ISSUE THREAD

**Issue by tuxmartin** [AddReminders/Reminders-in-RocketChat#11] opened 2022-07-13 19:15 UTC
Hello, I updated Reminder app (from Marketplace) about one hour ago.

Before that I had version 2.1.3. Now I have version 2.3.0 and in message menu (three dots) there is no "remind me" link.

I tried remove and install app again. It doesn't help.

Rocket.Chat server 4.8.1 snap, Debian 11.

How can I fix it?

**Comment by saschafoerster** [comment] 2022-07-13 19:17
Same here. As a workaround I use /remind.

**Comment by murtaza98** [comment] 2022-07-14 18:29
Hey guys, Sorry I'm not able to reproduce this issue on the given versions. However I do notice a similar issue when I was updating the app on the open server which has multiple instances running. In my case, it didn't update all the instances and rather disabled it on them, when I updated this app. So I had to restart all of them to make the app run across all of them. If you guys also have similar deployment setup, please consider restarting all the instances to make sure app is installed properly

**Comment by tuxmartin** [comment] 2022-07-14 19:11
@murtaza98 I tried restart Rocket.Chat (`systemctl restart snap.rocketchat-server.rocketchat-server.service`), but it doesn't help :-(

**Comment by saschafoerster** [comment] 2022-07-14 19:50
I am using docker and restarted, nothing shows up. 

```
Version
4.8.1
Version der Anwendungs-Engine
1.32.0
Node-Version
v14.18.3
Datenbankmigration
265 (Juli 11, 2022 23:50)
MongoDB
4.4.14 / wiredTiger (oplog Aktiviert)
Details festschreiben
HEAD: (0b106e364) 
Zweig: HEAD
PID
23
```

I am using the Remind-App from the marketplace, I updated it manually in the backend, then I restarted RocketChat. 
Remind-App is on version 2.3.0 

Nothing special in my logs: 

```
I20220714-19:46:56.591(0) LocalStore: store created at  
I20220714-19:46:56.593(0) LocalStore: store created at  
I20220714-19:46:56.595(0) LocalStore: store created at  
{"level":40,"time":"2022-07-14T19:47:06.962Z","pid":23,"hostname":"cd4f2398c7f0","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"} 
{"level":40,"time":"2022-07-14T19:47:21.466Z","pid":23,"hostname":"cd4f2398c7f0","name":"VoIPService","msg":"VoIP service already stopped"} 
{"level":51,"time":"2022-07-14T19:47:22.103Z","pid":23,"hostname":"cd4f2398c7f0","name":"Migrations","msg":"Not migrating, already at version 265"} 
I20220714-19:47:25.906(0) +--------------------------------------------------+ 
I20220714-19:47:26.068(0) |                  SERVER RUNNING                  | 
I20220714-19:47:26.069(0) +--------------------------------------------------+ 
I20220714-19:47:26.070(0) |                                                  | 
I20220714-19:47:26.070(0) |  Rocket.Chat Version: 4.8.1                      | 
I20220714-19:47:26.071(0) |       NodeJS Version: 14.18.3 - x64              | 
I20220714-19:47:26.071(0) |      MongoDB Version: 4.4.14                     | 
I20220714-19:47:26.072(0) |       MongoDB Engine: wiredTiger                 | 
I20220714-19:47:26.073(0) |             Platform: linux                      | 
I20220714-19:47:26.073(0) |         Process Port: 3000                       | 
I20220714-19:47:26.073(0) |             Site URL: ###  | 
I20220714-19:47:26.074(0) |     ReplicaSet OpLog: Enabled                    | 
I20220714-19:47:26.074(0) |          Commit Hash: 0b106e3645                 | 
I20220714-19:47:26.075(0) |        Commit Branch: HEAD                       | 
I20220714-19:47:26.076(0) |                                                  | 
I20220714-19:47:26.076(0) +--------------------------------------------------+ 
I20220714-19:47:28.911(0) Loaded the Apps Framework and loaded a total of 5 Apps! 
```

**Comment by murtaza98** [comment] 2022-07-15 08:23
Okay, thanks for confirming :+1: May I ask you to please check the app logs when you re-install the app, specifically the `initialize` event. Ideally, it should be like this :arrow_down: however if something fails there, those buttons would not get registered by the apps-engine which might cause this problem
![image](https://user-images.githubusercontent.com/34130764/179182177-38cec557-1da8-4e4e-b277-f33a9d598fd4.png)

Also can you guys please confirm if the version you are using is `2.3.0`. I know it's a silly question but I noticed that when I was installing the app on a brand new workspace from the marketplace, it had installed version `1.0.4` (which doesn't have the message action feature) instead of `2.3.0`. Hence I wanted to confirm this part.

PS: I was able to reproduce this issue on a brand new workspace however just once :see_no_evil: Once I tried to install it again on another new workspace it worked without issues. I'm right now trying to find a stable way to reproduce this issue. Also note, on the earlier workspace where I faced this issue, I was able to fix it by temporarily manually installing the reminder app from [here](https://github.com/AddReminders/Reminders-in-RocketChat/releases/tag/2.3.0) & then uninstalling it and reinstalling it again from the marketplace. So, if possible, please try to install the app manually and check if you're facing the same issue

**Comment by tuxmartin** [comment] 2022-07-15 09:44
@murtaza98 

I reinstalled app - still the same problem.

I reinstalled app again and there is "Remind me about this button". I dont't know how it si possible, but at this time it works :-D

![Výběr_1743](https://user-images.githubusercontent.com/1219067/179197385-ebf6fe95-dfbd-42a4-9b89-c3a3accd6122.png)

**Comment by murtaza98** [comment] 2022-07-15 12:57
@tuxmartin Glad, it worked for you and I agree with you, it's totally strange behaviour. I'm personally not a fan of re-installation of apps since users lose all their reminders :sweat:

**Comment by saschafoerster** [comment] 2022-07-15 21:34
I had to reconnect the workspace from rocket chat after uninstalling RemindMe, as I got this error, when I tried activating it again:
<img width="502" alt="Bildschirmfoto 2022-07-15 um 23 18 48" src="https://user-images.githubusercontent.com/1153741/179314051-64b949d3-f551-4327-a0bf-a49e0fcaee6a.png">
After that, I could reinstall it and then the button appeared again, just all reminders and license was lost.

**Comment by murtaza98** [comment] 2022-11-17 19:51
Hey guys, I hope you guys are still not facing this issue. So I'm closing this issue, however, if you're still facing this issue then feel free to contact me and we can re-open it and investigate further.

PS: A general tip: Due to all the instability around RocketChat's apps engine, I've noticed some apps not behaving properly and the only solution for solving those bugs is to always re-install the app completely. However, this is usually an issue with apps like this Reminder app which stores all its data within the app's storage itself which automatically gets pruned by the apps-engine once you delete the app which leads to the loss of all your important reminder data :disappointed: 

So in order to make sure you don't lose this important reminder data upon the event of re-installation, I'm trying to introduce a new internal backup and restore mechanism within the app itself for which you can find more information over [here](https://add-reminders.gitbook.io/docs/guides/other-guides/backup-and-restore-reminder-data). I highly recommend you to use it incase you're using this reminder app to not lose your data and always have a backup

**Closed as completed** 2022-11-17 19:51 UTC
